name: megl3-genet
# from template plasmabio-template-python
# with elements from https://github.com/pierrepo/plasma-env-cleblond-score-polygen.git
# and other elements from https://github.com/Scaburet/m1meg-gh-polygen.git
# channels priority
# see https://bioconda.github.io/
channels:
  - genomedk
  - bioconda
  - conda-forge
  - defaults
channel_priority: strict  
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  - bash_kernel
  - mscorefonts
  # Python environment
  - python>=3.9,<3.13
  - pip>=24.0
  - ipywidgets>=7.6,<8
  - numpy==1.26.4
  - pandas==2.3.1
  - scipy==1.13.1
  - matplotlib==3.8.4
  - seaborn==0.13.2
  - biopython==1.85
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  # jupyter-archive not compatible with the current JupyterLab <4
  - jupyter-archive
  - pip:
    # Jupyter-package-manager not compatible with the current JupyterLab <4
    #- jupyter-package-manager
    #- liftover>=1.1.13,<=1.3.1
    #- pyarrow==16.0.0
    #- Cython<3.1
    #- ldsc==2.0.1
    #- pybedtools==0.11.0
    #- polars==1.34.0
    #- scikit-allel==1.3.8
    #- statsmodels==0.14.5
    #- statannotations>=0.4.2
    - cyvcf2==0.31.4
    # Print module version
    - watermark
  # For the L3 Genet Euk course:
  - fastqc==0.12.1
  - bwa-mem2==2.2.1
  - samtools==1.21
  - bcftools==1.22
  - htslib==1.22.1
  # For the L3 GH practical course:
  - merlin=1.1.2
